# Generated by Django 2.2.5 on 2019-09-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('instagram_id', models.CharField(max_length=30)),
                ('flagged', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
